#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <nfc_hid_icons.h>

int32_t nfc_hid_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm nfc_hid!");

    return 0;
}
