#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <usb_hid_icons.h>

int32_t usb_hid_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm usb_hid!");

    return 0;
}
